export const CLUB_IDS = {
    AUBAGNE: 1,
    THIONVILLE: 2,
    CONCARNEAU: 3,
    ORLEANS: 4,
    BOURG: 5,
    VILLEFRANCHE: 6,
    ROUEN: 7,
    CANNES: 8,
    PARIS13: 9,
    QRM: 10,
    LA_ROCHE: 11,
    VERSAILLES: 12,
    FLEURY: 13,
    AMIENS: 14,
    CAEN: 15,
    VALENCIENNES: 16,
    BASTIA: 17,
    LE_PUY: 18,
} as const;